# Form implementation generated from reading ui file 'merge.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExceMerger(object):
    def setupUi(self, ExceMerger):
        ExceMerger.setObjectName("ExceMerger")
        ExceMerger.resize(756, 530)
        ExceMerger.setStyleSheet("QPushButton{\n"
"    font-size:16px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(255, 85, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size:16px;\n"
"    font-weight: bold;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ExceMerger)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=ExceMerger)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_choose_dir = QtWidgets.QPushButton(parent=ExceMerger)
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.horizontalLayout.addWidget(self.pushButton_choose_dir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lineEdit_dirpath = QtWidgets.QLineEdit(parent=ExceMerger)
        self.lineEdit_dirpath.setObjectName("lineEdit_dirpath")
        self.verticalLayout.addWidget(self.lineEdit_dirpath)
        self.label_2 = QtWidgets.QLabel(parent=ExceMerger)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidge_excel_path = QtWidgets.QListWidget(parent=ExceMerger)
        self.listWidge_excel_path.setObjectName("listWidge_excel_path")
        self.horizontalLayout_2.addWidget(self.listWidge_excel_path)
        self.pushButton_remove = QtWidgets.QPushButton(parent=ExceMerger)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_2.addWidget(self.pushButton_remove)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_merge = QtWidgets.QPushButton(parent=ExceMerger)
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.verticalLayout.addWidget(self.pushButton_merge)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ExceMerger)
        QtCore.QMetaObject.connectSlotsByName(ExceMerger)

    def retranslateUi(self, ExceMerger):
        _translate = QtCore.QCoreApplication.translate
        ExceMerger.setWindowTitle(_translate("ExceMerger", "合併Excel文件"))
        self.label.setText(_translate("ExceMerger", "請選擇要合併的Excel檔"))
        self.pushButton_choose_dir.setText(_translate("ExceMerger", "選擇目錄"))
        self.label_2.setText(_translate("ExceMerger", "請移除不需要的文件"))
        self.pushButton_remove.setText(_translate("ExceMerger", "移除文件"))
        self.pushButton_merge.setText(_translate("ExceMerger", "合併並保存結果"))
